#i started from https://downloads.portainer.io/ce2-18/portainer-agent-stack.yml
#and modified from there as needed
version: '3.8'

networks:
  portainer:
  registry_net:
    external: true

services:
  agent:
    image: portainer/agent:2.18.4-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.18.4-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
    volumes:
      - /mnt/portainer:/data
    networks:
      - portainer
      - registry_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]